- pkg:cargo/prometheus-client-derive-encode@0.4.0
- pkg:cargo/prometheus-client-derive-encode@0.4.1
- pkg:cargo/prometheus-client-derive-encode@0.4.2
- pkg:cargo/prometheus-client-derive-encode@0.5.0
