- pkg:cargo/prometheus_wireguard_exporter@0.1.0
- pkg:cargo/prometheus_wireguard_exporter@1.2.0
- pkg:cargo/prometheus_wireguard_exporter@1.2.1
- pkg:cargo/prometheus_wireguard_exporter@2.0.0
- pkg:cargo/prometheus_wireguard_exporter@2.0.1
- pkg:cargo/prometheus_wireguard_exporter@3.0.0
- pkg:cargo/prometheus_wireguard_exporter@3.0.1
- pkg:cargo/prometheus_wireguard_exporter@3.1.0
- pkg:cargo/prometheus_wireguard_exporter@3.1.1
- pkg:cargo/prometheus_wireguard_exporter@3.2.0
- pkg:cargo/prometheus_wireguard_exporter@3.2.1
- pkg:cargo/prometheus_wireguard_exporter@3.2.2
- pkg:cargo/prometheus_wireguard_exporter@3.2.3
- pkg:cargo/prometheus_wireguard_exporter@3.2.4
- pkg:cargo/prometheus_wireguard_exporter@3.3.0
- pkg:cargo/prometheus_wireguard_exporter@3.3.1
- pkg:cargo/prometheus_wireguard_exporter@3.3.2
- pkg:cargo/prometheus_wireguard_exporter@3.4.0
- pkg:cargo/prometheus_wireguard_exporter@3.4.1
- pkg:cargo/prometheus_wireguard_exporter@3.4.2
- pkg:cargo/prometheus_wireguard_exporter@3.5.0
- pkg:cargo/prometheus_wireguard_exporter@3.5.1
- pkg:cargo/prometheus_wireguard_exporter@3.6.1
- pkg:cargo/prometheus_wireguard_exporter@3.6.2
- pkg:cargo/prometheus_wireguard_exporter@3.6.3
- pkg:cargo/prometheus_wireguard_exporter@3.6.4
- pkg:cargo/prometheus_wireguard_exporter@3.6.5
- pkg:cargo/prometheus_wireguard_exporter@3.6.6
